### ISSUE TITLE
How would you create an instance of this using javascript?

### ISSUE THREAD

**Issue by supermoos** [1000ch/lazyload-image#6]
How would you create an instance of this using javascript?

**Comment by 1000ch** [comment]
```javascript
let img = document.createElement('img');
img.is = 'lazyload-image';
document.body.appendChild(img);
```

**Comment by supermoos** [comment]
Hmm, that does not seem to work for me? However, this does: document.createElement('img', 'lazyload-image'); Source: http://www.html5rocks.com/en/tutorials/webcomponents/customelements/#instantiating
